### ISSUE TITLE
adding missing images

### ISSUE THREAD

**Issue by MAVERICK-VF142** [yash19sinha/coffee-bean#9] opened 2023-10-06 15:53 UTC
in AMERICANO

**Comment by maitri-vv** [comment] 2023-10-06 16:35
hey! please provide description in brief about the changes. you can attach screenshot too.

**Comment by Anshul-004** [comment] 2023-10-06 16:51
@MAVERICK-VF142 I don't think any image is missing 
![image](https://github.com/yash19sinha/coffee-bean/assets/77480891/86871e20-6299-4951-9085-4fc1c885e591)

**Comment by Anshul-004** [comment] 2023-10-06 16:51
I can help center those images ,
you can assign it to me

**Comment by maitri-vv** [comment] 2023-10-06 17:27
hey! @Anshul-004  the issue is fixed. you can work on any new feature or enhancement :)

**Comment by Anshul-004** [comment] 2023-10-06 17:38
ok thanks

**Closed** 2023-10-06 20:19 UTC
